### ISSUE TITLE
Any way to customize the layout of the tabs?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [MdFarhanRaja/ColorFullTabLayout#3]
Suppose I want to have a customized layout of the tabs, of where and how the ImageView and TextView appear there, is there a way to do it?

**Comment by MdFarhanRaja** [comment]
Which type of customization you want ?

**Comment by MdFarhanRaja** [comment]
You can use following properties to your xml for cutomization ...
 
    app:atb_padding="10dp" // for padding
    app:atb_margin="10dp" // for margin
    app:atb_tabWidth="10dp" // for tab width
    app:atb_tabHeight="10dp" // for tab height
    app:atb_indicatorColor="#000000" // for tab indicator color
    app:atb_indicatorHeight="10dp" // for tab indicator height
    app:atb_selectedTabBackgroundColor="#000000" // for tab background
    app:atb_selectedTabTextColor="#000000" // for tab text color
    app:atb_selectedTabImageColor="#000000" // for tab image color
    app:atb_indicatorLineColor="#000000" // for tab indicator line color
    app:atb_noImage="false" // for hiding image 
    app:atb_noText="false" // for hiding text

    app:atb_imagePosition="top" // top,bottom,left or right

    app:atb_imageMargin="10dp" // for image margin
    app:atb_imageWidth="10dp" // for image width
    app:atb_imageHeight="10dp" // for image height
    app:atb_textMargin="10dp" // fot text margin
    app:atb_textSize="10dp" // for text size

**Comment by AndroidDeveloperLB** [comment]
I'd like to use this layout for each tab, for example:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_gravity="center"
    android:gravity="center"
    android:orientation="vertical"
    android:paddingBottom="4dp"
    android:paddingTop="4dp">

    <ImageView
        android:id="@+id/activity_main__tab__imageView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="4dp"
        android:duplicateParentState="true"
        android:scaleType="center"/>

    <TextView
        android:id="@+id/activity_main__tab__textView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:duplicateParentState="true"
        android:maxLines="1"
        android:singleLine="true"
        android:textColor="@color/activity_main__tab__text"
        android:textSize="12sp"/>

</LinearLayout>
```
And I use this for the tabs (using the support library tabs at the moment) :

 ```
       <android.support.design.widget.AppBarLayout
            android:id="@+id/activity_main__appBarLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:minHeight="48dp"
            android:theme="?attr/actionBarTheme">

            <android.support.design.widget.TabLayout
                android:id="@+id/activity_main__tabs"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="#fff"
                app:tabBackground="@drawable/activity_main__tab_background_selector"
                app:tabGravity="fill"
                app:tabIndicatorHeight="0px"/>
        </android.support.design.widget.AppBarLayout>
```

The problem I'm having is that the text get truncated for some reason, which is why I thought to try out some third libraries. Here's how it looks: 

![device-2017-05-10-132514](https://cloud.githubusercontent.com/assets/5357526/25894364/298b8122-3584-11e7-8e82-503a85daf955.png)

**Comment by MdFarhanRaja** [comment]
Yes i got it... You can use my library and customized according to your requirements...color, text size, image size etc...

**Comment by AndroidDeveloperLB** [comment]
How ? How do I use a customized layout?

**Comment by MdFarhanRaja** [comment]
No right now tab layout customization is not implemented.

**Comment by AndroidDeveloperLB** [comment]
Oh ok. That's what I asked about. Sorry and thank you
